def help():
    list_help = str('findust: 미세먼지 정보\n'
    + '    finedust: 서울의 미세먼지 정보\n'
    + '    finedust -l [location]: [location]의 미세먼지 정보\n' 
    + 'nowtemp: 날씨 정보\n'
    + '    nowtemp: 서울의 날씨 정보\n'
    + '    nowtemp -l [location]: [location]의 날씨 정보\n'
    + 'cmd: 명령어\n'
    + '    cmd: 명령어 입력 exit로 나감\n'
    + '    cmd -o [command]: [command]명령어 실행 단일 실행\n'
    + 'timer: 타이머\n'
    + '    rimer -c [time]: [time]에 있는 초만큼 카운트\n'
    + 'date: 날짜\n'
    + '    date: 날짜 정보\n'
    + 'classroom: 학교 페이지\n'
    + '    classroom: 학교 페이지 접속\n'
    + 'google: 구글\n'
    + '    google: 구글 접속\n'
    + 'clear: cls\n'
    + '    clear: 창 비우기\n'
    + 'crawling: 크롤링\n'
    + '    crawling -o [검색명]: [검색명]이미지 크롤링\n'
    + 'translate: 번역\n'
    + '    tr [언어]: [언어]번역(한글에서 영어는 안되뮤ㅠㅠ)\n'
    + 'email: 이메일 보내기\n'
    + '    email : 이메일 보내기\n')
    return list_help